package generatedbyassl.as.aes.coordinator.aeself_management.self_healing;

import java.io.Serializable;
import generatedbyassl.as.*;

/**
 * Generated by ASSL Framework
 * 
 * This is the Java class generated for 'InReconfiguration' (specified as FLUENT ASSL tier).
 */
public class INRECONFIGURATION
	extends ASSLFLUENT
	implements  Serializable
{

	/**
	 * Generated by ASSL Framework
	 * 
	 * This is a reference to the unique instance of 'INRECONFIGURATION' class.
	 */
	static private INRECONFIGURATION oInstance = null;
	/**
	 * Generated by ASSL Framework
	 * 
	 * Needed by the class because it implements the Serializable interface.
	 */
	static final long serialVersionUID = 0001L;

	/**
	 * Generated by ASSL Framework
	 * 
	 * Because this is a singleton class its constructor is private.
	 */
	private  INRECONFIGURATION (  )
	{
		vInitiatedByEvents.add( generatedbyassl.as.aes.coordinator.events.TOOLNOTFOUND.getInstance() );
		generatedbyassl.as.aes.coordinator.events.TOOLNOTFOUND.getInstance().addEventCatcher(this); //**** fluent registers for that event
		vTerminatedByEvents.add( generatedbyassl.as.aes.coordinator.events.RECONFIGURATIONDONE.getInstance() );
		generatedbyassl.as.aes.coordinator.events.RECONFIGURATIONDONE.getInstance().addEventCatcher(this); //**** fluent registers for that event
		vTerminatedByEvents.add( generatedbyassl.as.aes.coordinator.events.RECONFIGURATIONFAILED.getInstance() );
		generatedbyassl.as.aes.coordinator.events.RECONFIGURATIONFAILED.getInstance().addEventCatcher(this); //**** fluent registers for that event
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * This method returns the unique instance of 'INRECONFIGURATION' class.
	 */
	static public INRECONFIGURATION getInstance (  )
	{
		if ( null == oInstance ) 
		{
			oInstance = new INRECONFIGURATION();
		}
		return oInstance;
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * This method calls all the fluent-mapped actions in sequence.
	 */
	protected synchronized void callFluentActions (  )
	{
	}

}