package generatedbyassl.as.aes.host.aeself_management.self_healing;

import java.io.Serializable;
import generatedbyassl.as.*;

/**
 * Generated by ASSL Framework
 * 
 * This is the Java class generated for 'InToolInActive' (specified as FLUENT ASSL tier).
 */
public class INTOOLINACTIVE
	extends ASSLFLUENT
	implements  Serializable
{

	/**
	 * Generated by ASSL Framework
	 * 
	 * This is a reference to the unique instance of 'INTOOLINACTIVE' class.
	 */
	static private INTOOLINACTIVE oInstance = null;
	/**
	 * Generated by ASSL Framework
	 * 
	 * Needed by the class because it implements the Serializable interface.
	 */
	static final long serialVersionUID = 0001L;

	/**
	 * Generated by ASSL Framework
	 * 
	 * Because this is a singleton class its constructor is private.
	 */
	private  INTOOLINACTIVE (  )
	{
		vInitiatedByEvents.add( generatedbyassl.as.aes.host.events.TOOLINACTIVE.getInstance() );
		generatedbyassl.as.aes.host.events.TOOLINACTIVE.getInstance().addEventCatcher(this); //**** fluent registers for that event
		vTerminatedByEvents.add( generatedbyassl.as.aes.host.events.ISMSGTOOLINACTIVESENT.getInstance() );
		generatedbyassl.as.aes.host.events.ISMSGTOOLINACTIVESENT.getInstance().addEventCatcher(this); //**** fluent registers for that event
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * This method returns the unique instance of 'INTOOLINACTIVE' class.
	 */
	static public INTOOLINACTIVE getInstance (  )
	{
		if ( null == oInstance ) 
		{
			oInstance = new INTOOLINACTIVE();
		}
		return oInstance;
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * This method calls all the fluent-mapped actions in sequence.
	 */
	protected synchronized void callFluentActions (  )
	{
	}

}