package generatedbyassl.as.aes.coordinator.aeip.functions;

import java.io.Serializable;
import generatedbyassl.as.ASSLFUNCTION;

/**
 * Generated by ASSL Framework
 * 
 * This is the Java class generated for 'ReceivedToolInActiveMsg' (specified as FUNCTION ASSL tier).
 */
public class RECEIVEDTOOLINACTIVEMSG
	extends ASSLFUNCTION
	implements  Serializable
{

	/**
	 * Generated by ASSL Framework
	 * 
	 * This is a reference to the unique instance of 'RECEIVEDTOOLINACTIVEMSG' class.
	 */
	static private RECEIVEDTOOLINACTIVEMSG oInstance = null;
	/**
	 * Generated by ASSL Framework
	 * 
	 * Needed by the class because it implements the Serializable interface.
	 */
	static final long serialVersionUID = 0001L;

	/**
	 * Generated by ASSL Framework
	 * 
	 * Because this is a singleton class its constructor is private.
	 */
	private  RECEIVEDTOOLINACTIVEMSG (  )
	{
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * This method returns the unique instance of 'RECEIVEDTOOLINACTIVEMSG' class.
	 */
	static public RECEIVEDTOOLINACTIVEMSG getInstance (  )
	{
		if ( null == oInstance ) 
		{
			oInstance = new RECEIVEDTOOLINACTIVEMSG();
		}
		return oInstance;
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * Embeds statements to be performed by the function.
	 */
	public void DOES (  )
	{
		super.DOES();
		generatedbyassl.as.aes.host.aeip.channels.PRIVATE_LINK.getInstance().getMessage("generatedbyassl.as.aes.host.aeip.messages.TOOLINACTIVEMSG");
	}

}