package generatedbyassl.as.aes.host.controlloop;

import generatedbyassl.as.controlloop.ASSLEXECUTOR;

/**
 * Generated by ASSL Framework
 * 
 * This is the executor class of the host's control loop. An instance of this class participates in the monitor-analyzer-simulator-executor control loop of host.
 */
public class HOST_ASSLEXECUTOR
	extends ASSLEXECUTOR
{

	/**
	 * Generated by ASSL Framework
	 * 
	 * The superclass ASSLEXECUTOR makes this class fully functional. Put your modifications here (if any).
	 */

}