package generatedbyassl.as.aes.host.aeip.functions;

import java.io.Serializable;
import generatedbyassl.as.ASSLFUNCTION;

/**
 * Generated by ASSL Framework
 * 
 * This is the Java class generated for 'SendFunctionalityMsg' (specified as FUNCTION ASSL tier).
 */
public class SENDFUNCTIONALITYMSG
	extends ASSLFUNCTION
	implements  Serializable
{

	/**
	 * Generated by ASSL Framework
	 * 
	 * This is a reference to the unique instance of 'SENDFUNCTIONALITYMSG' class.
	 */
	static private SENDFUNCTIONALITYMSG oInstance = null;
	/**
	 * Generated by ASSL Framework
	 * 
	 * Needed by the class because it implements the Serializable interface.
	 */
	static final long serialVersionUID = 0001L;

	/**
	 * Generated by ASSL Framework
	 * 
	 * Because this is a singleton class its constructor is private.
	 */
	private  SENDFUNCTIONALITYMSG (  )
	{
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * This method returns the unique instance of 'SENDFUNCTIONALITYMSG' class.
	 */
	static public SENDFUNCTIONALITYMSG getInstance (  )
	{
		if ( null == oInstance ) 
		{
			oInstance = new SENDFUNCTIONALITYMSG();
		}
		return oInstance;
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * Embeds statements to be performed by the function.
	 */
	public void DOES (  )
	{
		super.DOES();
		generatedbyassl.as.aes.host.aeip.channels.PRIVATE_LINK.getInstance().putMessage("generatedbyassl.as.aes.host.aeip.messages.FUNCTIONALITYMSG", generatedbyassl.as.aes.host.aeip.messages.FUNCTIONALITYMSG.getInstance());
	}

}