package generatedbyassl.as.aes.coordinator.aeself_management;

import java.io.Serializable;
import generatedbyassl.as.ASSLPOLICY;

/**
 * Generated by ASSL Framework
 * 
 * This is the Java class generated for 'SELF_HEALING' (specified as SELF_HEALING ASSL tier).
 */
public class SELF_HEALING
	extends ASSLPOLICY
	implements  Serializable
{

	/**
	 * Generated by ASSL Framework
	 * 
	 * This is a reference to the unique instance of 'SELF_HEALING' class.
	 */
	static private SELF_HEALING oInstance = null;
	/**
	 * Generated by ASSL Framework
	 * 
	 * Needed by the class because it implements the Serializable interface.
	 */
	static final long serialVersionUID = 0001L;

	/**
	 * Generated by ASSL Framework
	 * 
	 * Because this is a singleton class its constructor is private.
	 */
	private  SELF_HEALING (  )
	{
		vFluents.put( "INUNFUNCTIONAL", generatedbyassl.as.aes.coordinator.aeself_management.self_healing.INUNFUNCTIONAL.getInstance() );
		vFluents.put( "INFUNCTIONALITYNOTIF", generatedbyassl.as.aes.coordinator.aeself_management.self_healing.INFUNCTIONALITYNOTIF.getInstance() );
		vFluents.put( "INCHECKINGHOSTTOOL", generatedbyassl.as.aes.coordinator.aeself_management.self_healing.INCHECKINGHOSTTOOL.getInstance() );
		vFluents.put( "INRECONFIGURATION", generatedbyassl.as.aes.coordinator.aeself_management.self_healing.INRECONFIGURATION.getInstance() );
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * This method returns the unique instance of 'SELF_HEALING' class.
	 */
	static public SELF_HEALING getInstance (  )
	{
		if ( null == oInstance ) 
		{
			oInstance = new SELF_HEALING();
		}
		return oInstance;
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * For each specified MAPPING, checks if the MAPPING conditions are fulfilled and if so spawn a thread to perform the MAPPING actions.
	 */
	public synchronized void doAllMappings (  )
	{
		//************************ MAPPING ***********************
		if ( generatedbyassl.as.aes.coordinator.aeself_management.self_healing.INUNFUNCTIONAL.getInstance().isFluentInitiated() ) 
		{
			//**** runs a thread that performs the actions mapped to these fluents
			Runnable actionsRunner = new Runnable()
			{
				/**
				 * Generated by ASSL Framework
				 * 
				 * This method runs the mapping thread until all the mapped actions have been performed.
				 */
				public void run (  )
				{
					try
					{
						generatedbyassl.as.aes.coordinator.actions.CHECKDEVICE.getInstance().perform(  );
					}
					catch ( Exception ex ) 
					{
						System.err.println( ex.getMessage() );
					}
				}

			};
			//**** creates and starts the thread if the latter is not currently running
			if ( !isMappingRunning( "INUNFUNCTIONAL" ) ) 
			{
				Thread runActions = new Thread(thrdgrMappings, actionsRunner, "INUNFUNCTIONAL");
				runActions.start();
			}
		}
		//************************ MAPPING ***********************
		if ( generatedbyassl.as.aes.coordinator.aeself_management.self_healing.INFUNCTIONALITYNOTIF.getInstance().isFluentInitiated() ) 
		{
			//**** runs a thread that performs the actions mapped to these fluents
			Runnable actionsRunner = new Runnable()
			{
				/**
				 * Generated by ASSL Framework
				 * 
				 * This method runs the mapping thread until all the mapped actions have been performed.
				 */
				public void run (  )
				{
					try
					{
						generatedbyassl.as.aes.coordinator.actions.CONFIRMFUNCTIONALITY.getInstance().perform(  );
					}
					catch ( Exception ex ) 
					{
						System.err.println( ex.getMessage() );
					}
				}

			};
			//**** creates and starts the thread if the latter is not currently running
			if ( !isMappingRunning( "INFUNCTIONALITYNOTIF" ) ) 
			{
				Thread runActions = new Thread(thrdgrMappings, actionsRunner, "INFUNCTIONALITYNOTIF");
				runActions.start();
			}
		}
		//************************ MAPPING ***********************
		if ( generatedbyassl.as.aes.coordinator.aeself_management.self_healing.INCHECKINGHOSTTOOL.getInstance().isFluentInitiated() ) 
		{
			//**** runs a thread that performs the actions mapped to these fluents
			Runnable actionsRunner = new Runnable()
			{
				/**
				 * Generated by ASSL Framework
				 * 
				 * This method runs the mapping thread until all the mapped actions have been performed.
				 */
				public void run (  )
				{
					try
					{
						generatedbyassl.as.aes.coordinator.actions.CHECKHOSTTOOLSTATUS.getInstance().perform(  );
					}
					catch ( Exception ex ) 
					{
						System.err.println( ex.getMessage() );
					}
				}

			};
			//**** creates and starts the thread if the latter is not currently running
			if ( !isMappingRunning( "INCHECKINGHOSTTOOL" ) ) 
			{
				Thread runActions = new Thread(thrdgrMappings, actionsRunner, "INCHECKINGHOSTTOOL");
				runActions.start();
			}
		}
		//************************ MAPPING ***********************
		if ( generatedbyassl.as.aes.coordinator.aeself_management.self_healing.INRECONFIGURATION.getInstance().isFluentInitiated() ) 
		{
			//**** runs a thread that performs the actions mapped to these fluents
			Runnable actionsRunner = new Runnable()
			{
				/**
				 * Generated by ASSL Framework
				 * 
				 * This method runs the mapping thread until all the mapped actions have been performed.
				 */
				public void run (  )
				{
					try
					{
						generatedbyassl.as.aes.coordinator.actions.RECONFIGURE.getInstance().perform(  );
					}
					catch ( Exception ex ) 
					{
						System.err.println( ex.getMessage() );
					}
				}

			};
			//**** creates and starts the thread if the latter is not currently running
			if ( !isMappingRunning( "INRECONFIGURATION" ) ) 
			{
				Thread runActions = new Thread(thrdgrMappings, actionsRunner, "INRECONFIGURATION");
				runActions.start();
			}
		}
	}

}