package generatedbyassl.as.aes.coordinator.actions;

import java.io.Serializable;
import generatedbyassl.as.ASSLACTION;

/**
 * Generated by ASSL Framework
 * 
 * This is the Java class generated for 'CheckHostToolStatus' (specified as ACTION ASSL tier).
 */
public class CHECKHOSTTOOLSTATUS
	extends ASSLACTION
	implements  Serializable
{

	/**
	 * Generated by ASSL Framework
	 * 
	 * This is a reference to the unique instance of 'CHECKHOSTTOOLSTATUS' class.
	 */
	static private CHECKHOSTTOOLSTATUS oInstance = null;
	/**
	 * Generated by ASSL Framework
	 * 
	 * Needed by the class because it implements the Serializable interface.
	 */
	static final long serialVersionUID = 0001L;

	/**
	 * Generated by ASSL Framework
	 * 
	 * Because this is a singleton class its constructor is private.
	 */
	private  CHECKHOSTTOOLSTATUS (  )
	{
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * This method returns the unique instance of 'CHECKHOSTTOOLSTATUS' class.
	 */
	static public CHECKHOSTTOOLSTATUS getInstance (  )
	{
		if ( null == oInstance ) 
		{
			oInstance = new CHECKHOSTTOOLSTATUS();
		}
		return oInstance;
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * Provides conditions to be fulfilled before processing the action.
	 */
	public boolean GUARDS (  )
	{
		boolean bResult = true;
		bResult =  generatedbyassl.as.aes.coordinator.aeself_management.self_healing.INCHECKINGHOSTTOOL.getInstance().isFluentInitiated()  ;
		return bResult;
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * Embeds statements to be performed by the action if the GURADS conditions are fulfilled.
	 */
	public void DOES (  )
	{
		super.DOES();
		generatedbyassl.as.aes.coordinator.aeip.functions.RECEIVEDTOOLINACTIVEMSG.getInstance().perform(  );
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * Triggers events in case the action is successfully performed.
	 */
	public void TRIGGERS (  )
	{
		if (  generatedbyassl.as.aes.coordinator.events.MSGTOOLINACTIVERECEIVED.getInstance().isPrompted()  ) 
		{
			generatedbyassl.as.aes.coordinator.events.TOOLNOTFOUND.getInstance().triggerEvent();
		}
		else
		{
			generatedbyassl.as.aes.coordinator.events.TOOLOK.getInstance().triggerEvent();
		}
	}

}