package generatedbyassl.as.aes.coordinator.actions;

import java.io.Serializable;
import generatedbyassl.as.ASSLACTION;

/**
 * Generated by ASSL Framework
 * 
 * This is the Java class generated for 'ConfirmFunctionality' (specified as ACTION ASSL tier).
 */
public class CONFIRMFUNCTIONALITY
	extends ASSLACTION
	implements  Serializable
{

	/**
	 * Generated by ASSL Framework
	 * 
	 * This is a reference to the unique instance of 'CONFIRMFUNCTIONALITY' class.
	 */
	static private CONFIRMFUNCTIONALITY oInstance = null;
	/**
	 * Generated by ASSL Framework
	 * 
	 * Needed by the class because it implements the Serializable interface.
	 */
	static final long serialVersionUID = 0001L;

	/**
	 * Generated by ASSL Framework
	 * 
	 * Because this is a singleton class its constructor is private.
	 */
	private  CONFIRMFUNCTIONALITY (  )
	{
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * This method returns the unique instance of 'CONFIRMFUNCTIONALITY' class.
	 */
	static public CONFIRMFUNCTIONALITY getInstance (  )
	{
		if ( null == oInstance ) 
		{
			oInstance = new CONFIRMFUNCTIONALITY();
		}
		return oInstance;
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * Provides conditions to be fulfilled before processing the action.
	 */
	public boolean GUARDS (  )
	{
		boolean bResult = true;
		bResult =  generatedbyassl.as.aes.coordinator.aeself_management.self_healing.INFUNCTIONALITYNOTIF.getInstance().isFluentInitiated()  ;
		return bResult;
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * Provides conditions to be ensured at the end of the action execution.
	 */
	public boolean ENSURES (  )
	{
		boolean bResult = true;
		bResult =  generatedbyassl.as.aes.coordinator.events.MSGFUNCTIONALITYRECEIVED.getInstance().isPrompted()  ;
		return bResult;
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * Embeds statements to be performed by the action if the GURADS conditions are fulfilled.
	 */
	public void DOES (  )
	{
		super.DOES();
		generatedbyassl.as.aes.coordinator.aeip.functions.RECEIVEFUNCTIONALITYMSG.getInstance().perform(  );
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * Triggers events in case the action is not successfully performed.
	 */
	public void ONERR_TRIGGERS (  )
	{
		generatedbyassl.as.autonomicnetwork.events.DEVICECRASHED.getInstance().triggerEvent();
	}

}